services:
  db:
    image: 'postgres:latest'
    container_name: postgres-trip
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_trip_data:/var/lib/postgresql/data/
    networks:
      - trip-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-trip
    ports:
      - "3333:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_trip_data:/var/lib/pgadmin
    networks:
      - trip-network


  web:
    restart: always
    image: julia4406/train_ticket_service_api_drf
    build: .
    container_name: trip-backend
    command: ["/bin/sh", "/usr/src/commands/run_trip_backend.sh"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app
    networks:
      - trip-network

volumes:
  postgres_trip_data:
    driver: local
  pgadmin_trip_data:

networks:
  trip-network:
    driver: bridge
