# Generated by Django 4.0.4 on 2025-02-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarriageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('seats_in_car', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_number', models.CharField(max_length=50)),
                ('carriages_quantity', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('carriage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriages', to='trip.carriagetype')),
            ],
        ),
    ]
