# Generated by Django 4.0.4 on 2025-02-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='total_seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
