# Generated by Django 4.0.4 on 2025-02-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_station_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip.crew')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip.route')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip.train')),
            ],
        ),
    ]
