# Generated by Django 4.0.4 on 2025-02-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='crew',
        ),
        migrations.AddField(
            model_name='trip',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='trips', to='trip.crew'),
        ),
    ]
