# Generated by Django 4.0.4 on 2025-02-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_order_ticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('car_num', 'seat_num', 'trip'), name='unique_car_num_seat_num_trip'),
        ),
    ]
